- .gitignore
Hi,
Is it should be possible to integrate this pull request ?
Without this commit, I've this in `git status`:
lg@steroids:~/Documents/IDEA/tulip$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
(use "git add <file>..." to include in what will be committed)
.idea/
pyvenv/
tulip.iml
nothing added to commit but untracked files present (use "git add" to track)
> add in .gitignore pyvenv and PyCharm files

- tests/test_queues.py
"python -m test" was running tests in the base class, which failed.
> Fix queue join tests for CPython's test runner.

- asyncio/coroutines.py
- asyncio/events.py
- asyncio/futures.py
- tests/test_tasks.py
Issue #222: Fix the @coroutine decorator for functions without __name__
attribute like functools.partial().
Enhance also the representation of a CoroWrapper if the coroutine
function is a functools.partial().
> Fix @coroutine for functions without __name__

- asyncio/compat.py
- asyncio/coroutines.py
- asyncio/events.py
- asyncio/futures.py
- asyncio/locks.py
- asyncio/streams.py
- asyncio/tasks.py
- asyncio/transports.py
Move compatibility helpers for the different Python versions to a new
asyncio.compat module.
> Add asyncio.compat module

- asyncio/tasks.py
- tests/test_tasks.py
See also issue #277.
Since `ensure_future()` is used by `loop.run_until_complete()`, I think it's a good idea to enable it for all awaitable objects (the ones that implement `__await__` in Python 3.5 and later).  With this PR it's valid to write `loop.run_until_complete(awaitable)`.
> Make ensure_future() accept awaitables in 3.5

- asyncio/streams.py
- tests/test_streams.py
> Raise error from drain() when socket is closed.

- asyncio/coroutines.py
- tests/test_pep492.py
This patch prevents coroutines to be awaited by more than one waiters simultaneously.  It affects only `async def` coroutines by patching `CoroWrapper.__await__`; I'm a bit hesitant to touch `CoroWrapper.__iter__`.
See issue #288 for details.
> Error if awaiting in parallel on the same coroutine (in debug mode)

- asyncio/test_utils.py
- tests/test_base_events.py
Couldn't push recent updates to CPython repo -- a push hook ensuring proper indentation failed. I think that using `subTest` is a great idea, we just need to make it not fail in 3.3.
> Make tests that use TestCase.subTest work in Python 3.3

- asyncio/test_support.py
- tests/test_pep492.py
On test envs without test.support tests were unable to run.  At first because of the following import error and then due to missing components in the test_support module.
:; python3 ./setup.py test
running test
running egg_info
writing dependency_links to asyncio.egg-info/dependency_links.txt
writing asyncio.egg-info/PKG-INFO
writing top-level names to asyncio.egg-info/top_level.txt
reading manifest file 'asyncio.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'asyncio.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
File "./setup.py", line 48, in <module>
ext_modules=extensions,
File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup …
> Copy/paste Python3.5 test.support to test_support

- asyncio/tasks.py
- tests/test_tasks.py
> Fix #325: Allow to pass None as a timeout value to disable timeout logic

- asyncio/subprocess.py
- tests/test_subprocess.py
Previously communicate(b"") was the same as communicate(), which caused
subprocesses waiting for input to hang. Without this fix, the new test hangs forever.
I originally submitted this this as https://github.com/python/cpython/pull/33.
> make asyncio's communicate() handle empty input

- tests/test_events.py
These are too specific to CPython which emits:
"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)"
> ease the cert failed regex

- asyncio/base_events.py
- asyncio/events.py
- tests/test_base_events.py
This PR implements a new event loop method `get_exception_handler()`. All other `set_*` methods have a corresponding `get_*` method. See also issue #340.
> Add 'loop.get_exception_handler()' method.

- asyncio/base_events.py
- asyncio/base_subprocess.py
- asyncio/events.py
- asyncio/futures.py
- asyncio/locks.py
- asyncio/proactor_events.py
- asyncio/queues.py
- asyncio/selector_events.py
- asyncio/streams.py
- asyncio/tasks.py
- asyncio/unix_events.py
- asyncio/windows_events.py
- tests/test_futures.py
This PR adds a new API -- `loop.create_future()` (see discussion in #282 for details).
> Add new loop.create_future() method.

- asyncio/selector_events.py
- tests/test_selector_events.py
In ``BaseSelectorEventLoop.sock_connect()``, an address is resolved if needed, but
``getaddrinfo()`` isn't called with the socket's parameters (family, proto, etc).
If the resolved address mismatch the socket type, the connection fails.
For instance, if ``getaddrinfo()`` returns an IPv6 (``AF_INET6``) resolution and the
socket is of family ``AF_INET``, ``sock_connect()`` eventually raises a ``TypeError``.
This PR is a follow-up to #357.
> Use socket specs for getaddrinfo() in sock_connect()

- appveyor.yml
- asyncio/base_events.py
- tests/test_events.py
This addresses: https://bugs.python.org/issue27392
> Provide an API to handle connections that are accepted outside of ayncio

- setup.py
Fixing #386 386
Signed-off-by: Sorin Sbarnea <sorin.sbarnea@gmail.com>
> #386 Added version check to prevent installation on Python < 3.3.0

- asyncio/locks.py
Fixes http://bugs.python.org/issue27585
> Avoid deadlock when a cancelled future is in self._waiters.

- asyncio/unix_events.py
- tests/test_events.py
Here's a pull request designed to fix the issue reported in #369.
_UnixWritePipeTransport selects for read on write pipes to detect when
the remote end of the pipe is closed. This works for unidirectional FIFOs
and dedicated socket pairs where nothing is written to the read side of
the pair, but it can cause problems with devices or sockets where
bidirectional I/O is being done.
This commit changes _UnixWritePipeTransport to only select for read on
sockets and FIFOs (on OSes which support that), and not on character
devices. When connect_write_pipe() is used on those devices,
end-of-file will need to be detected using a read pipe which accepts
inputs from the device.
No change is made to how sockets are handled, so passing in a socket
used for bidirectional I/O to connect_write_pipe() is …
> Don't select for read on character devices in _UnixWritePipeTransport

- asyncio/unix_events.py
Here's a pull request designed to fix the issue reported in #368.
This commit re-orders the initialization code in the _UnixReadPipeTransport
and _UnixWritePipeTransport constructors to make sure all members are
assigned a value, even in the case where ValueError is raised due to
an incompatible type of pipe. This avoids exceptions being raised in
__repr__() due to the missing members.
In the case where ValueError is raised, this commit also clears the values
of _pipe, _fileno, and _protocol since this transport isn't returned,
avoiding a spurious "unclosed transport" warning when the object is
garbage-collected.
> Fix ordering issues in UNIX read/write pipe transport constructors

- tests/test_events.py
When running the asyncio unit tests, I noticed that I was seeing the
following error from test_ssl_connect_accepted_socket():
/Volumes/ronf/src/asyncio/asyncio/sslproto.py:328: ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x10d7d57b8>
warnings.warn("unclosed transport %r" % self, ResourceWarning)
This commit fixes this error by calling close on the transport which is
opened rather than calling close on the socket of the accepted
connection used to create it.
> Fix an unclosed transport error in test_events

- asyncio/selector_events.py
This PR enables `TCP_NODELAY` for all TCP transports.
> Set TCP_NODELAY on TCP transports by default

- asyncio/tasks.py
Resolves #432. This is probably the best performing solution. The workaround for a programmer that wishes their coroutine objects to be undertaken in a deterministic order is for them to schedule the execution on the loop themselves with `asyncio.ensure_future` or `loop.create_task` before calling `asyncio.gather`.
> Document gather's undeterministic scheduling of awaitables and coroutines

- asyncio/coroutines.py
- tests/test_tasks.py
Following #429, this PR makes the signature of CoroWrapper.throw compatible with gen.throw.
The signature of gen.throw is the same in python 3.3 - 3.5. Unless I'm missing something, the patch shouldn't change anything for the current implementation of asyncio, since throw is only called explicitly in Task:
https://github.com/python/asyncio/blob/master/asyncio/tasks.py#L241
> make CoroWrapper.throw fully compatible with gen.throw

- asyncio/base_events.py
- tests/test_base_events.py
> Don't use getservbyname for non-numeric ports.

- asyncio/base_events.py
`_asyncgen_finalizer_hook` should wake up the loop in case it was called from another thread.
> Handle if async generators are GCed from another thread.

- asyncio/base_events.py
- asyncio/events.py
- asyncio/test_utils.py
- tests/test_base_events.py
- tests/test_events.py
- tests/test_futures.py
- tests/test_locks.py
- tests/test_pep492.py
- tests/test_proactor_events.py
- tests/test_queues.py
- tests/test_selector_events.py
- tests/test_sslproto.py
- tests/test_streams.py
- tests/test_subprocess.py
- tests/test_tasks.py
- tests/test_unix_events.py
- tests/test_windows_events.py
As discussed in [1] and [2], this PR makes `asyncio.get_event_loop()` to always return the currently running event loop when it is called from a coroutine.
The patch adds two new functions: `asyncio._set_current_loop()` and `asyncio._get_current_loop()`.  Both functions are thread-specific and are considered as low-level APIs, intended to be used by third-party loop implementations only. Even though they have a leading underscore, they will be documented as public asyncio API.
`loop.run_forever()` is modified to call `asyncio._set_current_loop()` and `asyncio._get_current_loop()`.
`asyncio.get_event_loop()` is modified to check if there is a current loop set by calling `asyncio._get_current_loop()`.  If there is no current event loop, it returns the result of …
> Make get_event_loop() return the current loop if called from coroutines

- asyncio/base_events.py
- asyncio/unix_events.py
- tests/test_base_events.py
- tests/test_events.py
- tests/test_unix_events.py
Currently, `loop.create_server`, `loop.create_connection`, and `loop.connect_accepted_socket` accept any kind of socket, although they are documented (and used by asyncio users) as TCP API.
Allowing those methods to accept any kinds of sockets leads to hard to debug bugs.  For instance, aiohttp gunicorn worker simply passes all sockets to `create_server` (including UNIX sockets). We even have a unittest in asyncio that does that: `test_create_datagram_endpoint_sock` passes a UDP socket to `create_connection`.
TCP, UDP and UNIX sockets are different from each other and have some subtle API differences. We shouldn't allow to blindly pass any of them to `create_server` and other TCP APIs.
> Make loop TCP APIs accept only TCP streaming sockets

- asyncio/coroutines.py
- tests/test_tasks.py
This makes `asyncio.iscoroutinefunction` more robust and fixes issue #458.
> Fix iscoroutinefunction() to support mock/proxy obejcts

- asyncio/sslproto.py
- tests/test_sslproto.py
There were situations when yield from waiter hangs. For example if connection is aborted by peer before handshake completes.
> SSL hangs if connection_lost is called (#472)
